version: '3.9'

services:
  my-loads:
    build: ./
    command: ./wait-for-postgres.sh 172.18.0.1 ./my-loads
    ports:
      - "8085:8000"
    depends_on:
      - db
    environment:
      BD_MONOLITH: 'host=db user=tsvse dbname=monolith password=22war398 port=5432'
      BD_AUCTION: 'host=db user=tsvse dbname=auction_service password=22war398 port=5432'
      BD_PAYMENT: 'host=db user=tsvse dbname=payment_service password=22war398 port=5432'
      DB_PASSWORD: "22war398"

  db:
    container_name: postgres_container
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./.database/postgres/scheme:/var/lib/postgresql/data
      - ./pkg/database/sql/dump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "22war398"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - db

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "tsvve@bk.ru"
      PGADMIN_DEFAULT_PASSWORD: "22war398"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pkg/database/sql/dump:/home/dump
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - db

networks:
  db:
    driver: bridge